[package]
name = "structex"
version = "0.1.0"
edition = "2024"

[features]
default = ["regex"]
regex = ["dep:regex"]

[dependencies]
regex = { version = "1", optional = true }

[dev-dependencies]
handlebars = "6.3.2"
simple_test_case = "1.3.0"
